# Generated by Django 3.0.2 on 2021-05-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_constantes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constantes',
            new_name='Constante',
        ),
    ]
